### ISSUE TITLE
create a new "thing"

### ISSUE THREAD

**Issue by angelo-v** [pod-os/PodOS#18]
>As an early adopter of Solid
>I want to store any things to my Pod
>so that I can manage knowledge about things I care about
>without waiting for specific apps to emerge

## Acceptance criteria

- [x] I can create a new Thing of any type from well-know vocabularies
- [x] The thing is created in a new document relative to the current location in PodOS Browser
  - if container, in that container
  - if file, in container of that file
  - if non-information-resource, container of the document of that resource
- [x] I can give the thing a name which is stored as `rdfs:label`
- [x] The slugified name is used as the name of the new file, e.g. "My cake recipe" -> "my-cake-recipe"
- [x] I can see the new URI of the resource that will be created
- [x] After creating PodOS Browser navigates to that new resource

**Comment by angelo-v** [comment]
## Open Tasks

- [ ] style the new thing dialog
- [ ] add form for new thing
- [ ] add URI preview
- [ ] wire up core logic
- [ ] add button to header or similar place
- [ ] navigate to created resource
- [ ] e2e test

**Comment by josephguillaume** [comment]
Just wondering what the rationale is for "The thing is created in a new document relative to the current location in PodOS Browser"?

 Is this a normative decision (good/best practice), or simply a minimum acceptance criterion?

At the moment I often have multiple things in one document, so it would make more sense in my use case that if the current location is an rdf document, then the thing is created as `<#slug>` rather than `<slug#it>` in the same container.

**Comment by angelo-v** [comment]
You are right on that. This is a minmal version to be able to create a thing and a reasonable default in my opinion. The user should be able to adjust the location / URI if she likes to in a future version.

**Comment by josephguillaume** [comment]
Thanks! Good to get a feeling about how opinionated you're planning PodOS to be.
